"""
LLM Provider for NETHRA AI — Google Gemini via google-genai SDK.

Authentication notes (verified against official docs, 2026):
  - Google AI Studio now issues "AQ." prefixed API keys (Authorization Keys).
    These replaced the legacy "AIza" format and are fully supported by
    google-genai >= 1.0.0.  Do NOT assume AQ. keys are invalid.
  - Pass the key via `api_key=` in genai.Client().  The SDK handles the
    correct HTTP Authorization header internally.
  - Do NOT pass the key as a Bearer token manually; the SDK does this.
  - Reference: https://ai.google.dev/gemini-api/docs/api-key

Model notes:
  - "gemini-1.5-pro" is still valid but being deprecated in favour of
    the Gemini 2.x generation.
  - "gemini-2.5-flash" is the current recommended cost-efficient model.
  - "gemini-2.5-pro"  is the current recommended high-quality model.
  - To list all models available to your key:
      for m in client.models.list(): print(m.name)
"""

import logging
import traceback

from google import genai

from app.core.config import settings

logger = logging.getLogger(__name__)


class LLMProvider:
    def __init__(self):
        self.api_key = settings.GEMINI_API_KEY

        if not self.api_key:
            raise RuntimeError(
                "GEMINI_API_KEY is not set in backend/.env. "
                "Generate a key at https://aistudio.google.com/apikey "
                "and add it as:  GEMINI_API_KEY=AQ.your_key_here"
            )

        # Use gemini-2.5-flash — fast, capable, and available on the free tier.
        # Switch to "gemini-2.5-pro" for higher quality at higher cost.
        self.model_name = "gemini-2.5-flash"

        # AQ. keys are valid; pass directly to api_key=.
        # The SDK handles Authorization headers internally.
        self.client = genai.Client(api_key=self.api_key)

    def generate_response(
        self,
        context: str,
        question: str,
        instructions: str,
        history: list = None,
    ) -> str:
        # Build prompt with history, then question, then instructions.
        # IMPORTANT: Source attribution is generated by the backend retrieval layer.
        # The LLM must NOT produce a "Sources:" or "References:" section.
        prompt_parts = [context]

        if history:
            prompt_parts.append("\n=== Conversation History ===")
            for msg in history[-5:]:
                role = "Investigator" if msg.get("role") == "user" else "Assistant"
                prompt_parts.append(f"{role}: {msg.get('content')}")

        prompt_parts.append(
            f"\n=== Investigator Question ===\n{question}\n\n{instructions}"
            "\n\nREMINDER: Do NOT include a Sources, References, or Citations "
            "section. The system appends source attribution automatically."
        )
        prompt = "\n".join(prompt_parts)

        logger.debug(
            "Calling Gemini | model=%s | prompt_chars=%d",
            self.model_name,
            len(prompt),
        )

        try:
            response = self.client.models.generate_content(
                model=self.model_name,
                contents=prompt,
            )
            return response.text
        except Exception as e:
            logger.error(
                "Gemini API call failed.\n"
                "Model: %s | Prompt length: %d chars\n%s",
                self.model_name,
                len(prompt),
                traceback.format_exc(),
            )
            raise RuntimeError(f"LLM generation failed: {e}") from e
