"""Add LLM to ExtractionMethodNER

Revision ID: b27f24d6e6b6
Revises: 053e4fa17d06
Create Date: 2026-07-12 19:46:18.112496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b27f24d6e6b6'
down_revision: Union[str, Sequence[str], None] = '053e4fa17d06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_audit_logs_evidence_id'), ['evidence_id'], unique=False)

    with op.batch_alter_table('extracted_entities', schema=None) as batch_op:
        batch_op.alter_column('extraction_method',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('SPACY', 'REGEX', 'STRUCTURED', 'LLM', name='extractionmethodner'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracted_entities', schema=None) as batch_op:
        batch_op.alter_column('extraction_method',
               existing_type=sa.Enum('SPACY', 'REGEX', 'STRUCTURED', 'LLM', name='extractionmethodner'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_evidence_id'))
        batch_op.alter_column('details',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###
